shared:
  build: infra/packer/container/shared
  volumes:
    - ./code/backend:/var/www/html

logstash:
  build: infra/packer/container/logstash
  links:
    - elasticsearch

nginx:
  build: infra/packer/container/nginx
  ports:
    - 8080:80
  links:
    - phpfpm
    - logstash
  volumes_from:
    - shared

redis:
  build: infra/packer/container/redis
  links:
    - logstash

phpfpm:
  build: infra/packer/container/phpfpm
  links:
    - redis
    - postgres
    - elasticsearch
    - logstash
    - mailhog
  volumes_from:
    - shared

worker:
  build: infra/packer/container/worker
  links:
    - redis
    - postgres
    - elasticsearch
    - logstash
    - mailhog
  volumes_from:
    - shared

postgres:
  build: infra/packer/container/postgres
  ports:
    - 5432:5432

elasticsearch:
  build: infra/packer/container/elasticsearch
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  build: infra/packer/container/kibana
  ports:
    - 5601:5601
  links:
    - elasticsearch

mailhog:
  build: infra/packer/container/mailhog
  ports:
    - 8025:8025

#cli:
#  build: docker/cli
#  links:
#    - redis
#    - postgres
#    - elasticsearch
#  volumes_from:
#    - shared
