shared:
  build: docker/shared
  volumes:
    - ./code/backend:/var/www/html

logstash:
  build: docker/logstash
  links:
    - elasticsearch

nginx:
  build: docker/nginx
  ports:
    - 8080:80
  links:
    - php
    - logstash
  volumes_from:
    - shared

redis:
  build: docker/redis
  links:
    - logstash

php:
  build: docker/php
  links:
    - redis
    - postgres
    - elasticsearch
    - logstash
  volumes_from:
    - shared

worker:
  build: docker/worker
  links:
    - redis
    - postgres
    - elasticsearch
  volumes_from:
    - shared

postgres:
  build: docker/postgres
  ports:
    - 5432:5432

elasticsearch:
  build: docker/elasticsearch
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  build: docker/kibana
  ports:
    - 5601:5601
  links:
    - elasticsearch
