shared:
  build: docker/shared
  volumes:
    - ./code:/var/www/html

nginx:
  build: docker/nginx
  ports:
    - 8080:80
  links:
    - php
  volumes_from:
    - shared

redis:
  build: docker/redis

php:
  build: docker/php
  links:
    - redis
    - postgres
    - elasticsearch
  volumes_from:
    - shared

postgres:
  build: docker/postgres
  ports:
    - 5432:5432

elasticsearch:
  build: docker/elasticsearch
  ports:
    - 9200:9200
    - 9300:9300