shared:
  build: docker/shared
  volumes:
    - ./code/backend:/var/www/html

logstash:
  build: docker/logstash
  links:
    - elasticsearch

postgres:
  build: docker/postgres
  ports:
    - 5432:5432
  volumes:
    - ./data/postgres:/data

nginx:
  build: docker/nginx
  ports:
    - 8080:80
  links:
    - phpfpm
    - logstash
  volumes_from:
    - shared

redis:
  build: docker/redis
  links:
    - logstash

phpfpm:
  build: docker/phpfpm
  links:
    - redis
    - postgres
    - elasticsearch
    - logstash
    - mailhog
  volumes_from:
    - shared

worker:
  build: docker/worker
  links:
    - redis
    - postgres
    - elasticsearch
    - logstash
    - mailhog
  volumes_from:
    - shared

elasticsearch:
  build: docker/elasticsearch
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - ./data/elasticsearch:/data

kibana:
  build: docker/kibana
  ports:
    - 5601:5601
  links:
    - elasticsearch

mailhog:
  build: docker/mailhog
  ports:
    - 8025:8025

#cli:
#  build: docker/cli
#  links:
#    - redis
#    - postgres
#    - elasticsearch
#  volumes_from:
#    - shared
